agimus_controller_node:
  ros__parameters:
    ocp:
      dt: 0.01
      dt_factor_n_seq:
        factors: [1, 2, 4]
        dts: [10, 10, 9]
      horizon_size: 30
      armature: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      gripper_weight: 500.0
      state_weight: 5.0
      control_weight: 0.001
      max_qp_iter: 100
      max_iter: 10
      activate_callback: False
      nb_threads: 6
      collision_safety_margin: 0.02
      activation_distance_threshold: 0.04
    publish_debug_data: True
    rate: 100.0
    free_flyer: False
    collision_as_capsule: True
    self_collision: False
    collision_pairs_names: ["cp_1"]
    cp_1:
      first: "fer_link7_sc_capsule_0"
      second: "obstacle1_capsule_0"
